[opener]
edit = [
	{ run = 'hx "$@"', block = true },
]

[mgr]
ratio = [2, 3, 5]

[preview]
wrap = "yes"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
